spring.application.name=LostPaw
server.port=8081

# Load local .env file if it exists
spring.config.import=optional:file:.env[.properties]

# Database connection
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/lostpaw}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Multipart upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=30MB

# Storage directories
storage.images-dir=../storage/images
storage.documents-dir=../storage/contracts

# Frontend
app.frontend-url=http://localhost:5173

# JSON dates
spring.jackson.serialization.write-dates-as-timestamps=false

# JWT
jwt.secret=${JWT_SECRET}

# Mail
mail.smtp.ssl.protocols=TLSv1.2

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Freemarker
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftl